version: 2
jobs:

  build:
    docker:
      - image: jekyll/jekyll:3.5.0
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: cd /srv/jekyll
      - run: mkdir -p _site
      - run: jekyll build

workflows:
  version: 2
  build:
    jobs:
      - build
