version: 2
jobs:

  build:
    docker:
      - image: jekyll/jekyll:3.5.0
    working_directory: /srv/jekyll
    steps:
      - checkout
      - run:
          name: Build Jekyll markdown into static files for deployment
          command: deploy-scripts/scripts/build-jekyll.sh
          environment:
            JEKYLL_ENV: production
      - persist_to_workspace:
          root: /srv/jekyll
          paths:
            - _site

  containerise:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Authenticate google cloud
          command: deploy-scripts/scripts/authenticate-gcloud.sh
      - run:
          name: Build docker image
          command: docker build --tag "$DOCKER_CONTAINER_REGISTRY"/"$GCLOUD_PROJECT"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_SHA1" .
      - run:
          name: Push docker image
          command: docker push "$DOCKER_CONTAINER_REGISTRY"/"$GCLOUD_PROJECT"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_SHA1"

  deploy-production:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: Authenticate google cloud
          command: deploy-scripts/scripts/authenticate-gcloud.sh
      - run:
          name: Create and expose kubernetes deployment
          command: deploy-scripts/scripts/deploy.sh

workflows:
  version: 2
  build-containerise-deploy-production:
    jobs:
      - build
      - containerise:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-production:
          requires:
            - containerise
          filters:
            branches:
              only: master
