version: 2
jobs:

  build:
    docker:
      - image: jekyll/jekyll:3.5.0
    steps:
      - checkout
      - run: echo $(whoami)
      - run: echo $(pwd)
      - run: echo $(which jekyll)
      - run: jekyll --version

workflows:
  version: 2
  build:
    jobs:
      - build
