version: 2
jobs:

  build:
    docker:
      - image: jekyll/jekyll:3.5.0
    steps:
      - checkout
      - run: mkdir -p _site
      - run: jekyll build

workflows:
  version: 2
  build:
    jobs:
      - build
