version: 2
jobs:

  build:
    steps:
      - checkout
      - setup_remote_docker
      - run: mkdir -p _site
      - run: docker run --volume=$(pwd):/srv/jekyll --env JEKYLL_ENV=production jekyll/jekyll:3.5.0 jekyll build

workflows:
  version: 2
  build:
    jobs:
      - build
