version: 2
jobs:

  build:
    docker:
      - image: jekyll/jekyll:3.5.0
    working_directory: /srv/jekyll
    steps:
      - checkout
      - run:
          name: Build Jekyll markdown into static files for deployment
          command: deploy-scripts/scripts/build-jekyll.sh
          environment:
            JEKYLL_ENV: production
      - persist_to_workspace:
          root: /srv/jekyll
          paths:
            - _site

  containerise:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Authenticate google cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode --ignore-garbage > $HOME/gcloud-service-key.json && \
            gcloud auth activate-service-account --key-file=$HOME/gcloud-service-key.json && \
            gcloud config set project homepage-201807 && \
            gcloud config set compute/zone us-central1-a && \
            gcloud auth configure-docker
      - run:
          name: Build docker image
          command: docker build --tag "gcr.io/homepage-201807/blah:$CIRCLE_SHA1" .
      - run:
          name: Push docker image
          command: docker push "gcr.io/homepage-201807/blah:$CIRCLE_SHA1"

  deploy-production:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: Authenticate google cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json && \
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json && \
            gcloud config set project homepage-201807 && \
            gcloud config set compute/zone us-central1-a && \
            gcloud auth configure-docker && \
            gcloud container clusters get-credentials cluster-1
      - run:
          name: Create kubernetes deployment and expose deployment
          command: |
            apt-get -y install gettext-base && \
            cd deploy-scripts/kubernetes && \
            envsubst < deployment.yml | kubectl apply -f - && \
            kubectl create -f service.yml

workflows:
  version: 2
  build-containerise-deploy-production:
    jobs:
      - build
      - containerise:
          requires:
            - build
      - deploy-production:
          requires:
            - containerise
