apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: $CIRCLE_PROJECT_REPONAME
  labels:
    name: $CIRCLE_PROJECT_REPONAME
spec:
  replicas: 1
  selector:
    matchLabels:
      name: $CIRCLE_PROJECT_REPONAME
  template:
    metadata:
      labels:
        name: $CIRCLE_PROJECT_REPONAME
    spec:
      containers:
      - env:
        image: $DOCKER_CONTAINER_REGISTRY/$GCLOUD_PROJECT/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
        imagePullPolicy: Always
        name: homepage-blog
        ports:
        - containerPort: 80
