apiVersion: v1
kind: Service
metadata:
  name: $CIRCLE_PROJECT_REPONAME
  labels:
    name: $CIRCLE_PROJECT_REPONAME
spec:
  type: LoadBalancer
  loadBalancerIP: 35.202.53.96
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: $CIRCLE_PROJECT_REPONAME
